server:
  port: 8081

spring:
  datasource:
    url: jdbc:sqlserver://localhost\\SQLEXPRESS:1433;databaseName=cart_and_checkout_db;encrypt=true;trustServerCertificate=true
    username: sa
    password: root$123
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.SQLServerDialect

  cloud:
    gateway:
      routes:
        - id: address-service
          uri: http://localhost:8080
          predicates:
            - Path=/Address/**

        - id: cart-service
          uri: http://localhost:8080
          predicates:
            - Path=/cart/**

        - id: addtocart-service
          uri: http://localhost:8080
          predicates:
            - Path=/AddtoCart/**
